apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  creationTimestamp: "2024-01-18T08:22:34Z"
  labels:
    kube-aggregator.kubernetes.io/automanaged: onstart
  name: v1beta2.flowcontrol.apiserver.k8s.io
spec:
  group: flowcontrol.apiserver.k8s.io
  groupPriorityMinimum: 16100
  version: v1beta2
  versionPriority: 15
