apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    rbac.authorization.kubernetes.io/autoupdate: "true"
  creationTimestamp: "2024-01-18T08:22:35Z"
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system:controller:endpointslice-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:controller:endpointslice-controller
subjects:
- kind: ServiceAccount
  name: endpointslice-controller
  namespace: kube-system
