apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"katafygio","chart":"katafygio-0.5.1","heritage":"Helm","release":"katafygio"},"name":"katafygio","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"katafygio","release":"katafygio"}},"strategy":{"type":"Recreate"},"template":{"metadata":{"labels":{"app":"katafygio","chart":"katafygio-0.5.1","heritage":"Helm","release":"katafygio"}},"spec":{"containers":[{"args":["--healthcheck-port=8080","--log-level=info","--log-output=stdout","--resync-interval=300","--exclude-kind=replicasets","--exclude-kind=endpoints","--exclude-kind=events"],"image":"svl-artifactory.juniper.net/atom-docker/cn2/trohit7/mutate:applabel1","imagePullPolicy":"Always","livenessProbe":{"httpGet":{"path":"/health","port":"http"},"initialDelaySeconds":60,"periodSeconds":10,"timeoutSeconds":10},"name":"katafygio","ports":[{"containerPort":8080,"name":"http","protocol":"TCP"}],"readinessProbe":{"httpGet":{"path":"/health","port":"http"},"initialDelaySeconds":30,"periodSeconds":20,"timeoutSeconds":10},"resources":{},"volumeMounts":[{"mountPath":"/var/lib/katafygio","name":"katafygio-data"},{"mountPath":"/etc/katafygio","name":"config-volume"}]}],"securityContext":{"fsGroup":65534},"serviceAccountName":"katafygio","volumes":[{"name":"katafygio-data","persistentVolumeClaim":{"claimName":"katafygio"}},{"configMap":{"name":"katafygio-config"},"name":"config-volume"}]}}}}
  creationTimestamp: "2024-03-04T11:19:19Z"
  labels:
    app: katafygio
    chart: katafygio-0.5.1
    heritage: Helm
    release: katafygio
  name: katafygio
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: katafygio
      release: katafygio
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: katafygio
        chart: katafygio-0.5.1
        heritage: Helm
        release: katafygio
    spec:
      containers:
      - args:
        - --healthcheck-port=8080
        - --log-level=info
        - --log-output=stdout
        - --resync-interval=300
        - --exclude-kind=replicasets
        - --exclude-kind=endpoints
        - --exclude-kind=events
        image: svl-artifactory.juniper.net/atom-docker/cn2/trohit7/mutate:applabel1
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: http
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        name: katafygio
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: http
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 10
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/katafygio
          name: katafygio-data
        - mountPath: /etc/katafygio
          name: config-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 65534
      serviceAccount: katafygio
      serviceAccountName: katafygio
      terminationGracePeriodSeconds: 30
      volumes:
      - name: katafygio-data
        persistentVolumeClaim:
          claimName: katafygio
      - configMap:
          defaultMode: 420
          name: katafygio-config
        name: config-volume
