apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"gitea"},"name":"gitea","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"gitea"}},"template":{"metadata":{"labels":{"app":"gitea"}},"spec":{"containers":[{"image":"gitea/gitea:latest","name":"gitea","ports":[{"containerPort":3000,"name":"gitea"},{"containerPort":22,"name":"git-ssh"}],"volumeMounts":[{"mountPath":"/data","name":"git-volume"}]}],"volumes":[{"name":"git-volume","persistentVolumeClaim":{"claimName":"git-volume"}}]}}}}
  creationTimestamp: "2024-02-07T11:33:01Z"
  labels:
    app: gitea
  name: gitea
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: gitea
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: gitea
    spec:
      containers:
      - image: gitea/gitea:latest
        imagePullPolicy: Always
        name: gitea
        ports:
        - containerPort: 3000
          name: gitea
          protocol: TCP
        - containerPort: 22
          name: git-ssh
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data
          name: git-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: git-volume
        persistentVolumeClaim:
          claimName: git-volume
